version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CREATE_TABLE: "no"
      DB_SWITCH: "on"
      TOKEN: 6403961384:AAEVasFvoPENNaiHBBFsCcrnJ_G16Wo4TNs
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable
